[profile.default]
src = "src"
out = "out"
libs = ["lib"]
"openzeppelin-contracts" = "github:OpenZeppelin/openzeppelin-contracts"
via_ir = true
optimizer = true
optimizer_runs = 200


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Remappings should be outside any section, or use remappings array:
remappings = [
  '@openzeppelin/=lib/openzeppelin-contracts/'
]